DROP PROCEDURE IF EXISTS sp_InsertRol;
GO

DROP PROCEDURE IF EXISTS sp_InsertStatus;
GO

DROP PROCEDURE IF EXISTS sp_InsertCategory;
GO

DROP PROCEDURE IF EXISTS sp_InsertUser;
GO

DROP PROCEDURE IF EXISTS sp_InsertClient;
GO

DROP PROCEDURE IF EXISTS sp_InsertProduct;
GO

DROP PROCEDURE IF EXISTS sp_InsertOrder;
GO

DROP PROCEDURE IF EXISTS sp_InsertDetail;
GO
