DROP PROCEDURE IF EXISTS sp_UpdateRol;
GO

DROP PROCEDURE IF EXISTS sp_UpdateStatus;
GO

DROP PROCEDURE IF EXISTS sp_UpdateCategory;
GO

DROP PROCEDURE IF EXISTS sp_UpdateUser;
GO

DROP PROCEDURE IF EXISTS sp_UpdateClient;
GO

DROP PROCEDURE IF EXISTS sp_UpdateProduct;
GO

DROP PROCEDURE IF EXISTS sp_UpdateOrder;
GO

DROP PROCEDURE IF EXISTS sp_UpdateDetail;
GO
