-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2024-12-04 22:06:43 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE category (
    id_category      INTEGER NOT NULL,
    name             VARCHAR2(50) NOT NULL,
    creation_date    DATE NOT NULL,
    status_id_status INTEGER NOT NULL
);

ALTER TABLE category ADD CONSTRAINT category_pk PRIMARY KEY ( id_category );

CREATE TABLE client (
    id_user   INTEGER NOT NULL,
    id_client INTEGER NOT NULL,
    source    VARCHAR2(50) NOT NULL,
    reason    VARCHAR2(255) NOT NULL,
    address   VARCHAR2(255) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_user );

ALTER TABLE client ADD CONSTRAINT client_pkv1 UNIQUE ( id_client );

CREATE TABLE detail (
    id_detail          INTEGER NOT NULL,
    quantity           INTEGER NOT NULL,
    subtotal           FLOAT NOT NULL,
    product_id_product INTEGER NOT NULL,
    order_id_order     INTEGER NOT NULL
);

ALTER TABLE detail ADD CONSTRAINT detail_pk PRIMARY KEY ( id_detail );

CREATE TABLE "Order" (
    id_order         INTEGER NOT NULL,
    creation_date    DATE NOT NULL,
    address          VARCHAR2(255) NOT NULL,
    delivery_date    DATE NOT NULL,
    total            FLOAT NOT NULL,
    client_id_client INTEGER NOT NULL,
    user_id_user     INTEGER NOT NULL
);

ALTER TABLE "Order" ADD CONSTRAINT order_pk PRIMARY KEY ( id_order );

CREATE TABLE product (
    id_product           INTEGER NOT NULL,
    name                 VARCHAR2(50) NOT NULL,
    brand                VARCHAR2(50) NOT NULL,
    code                 VARCHAR2(50) NOT NULL,
    stock                INTEGER NOT NULL,
    price                FLOAT NOT NULL,
    creation_date        DATE NOT NULL,
    picture              BLOB NOT NULL,
    category_id_category INTEGER NOT NULL,
    status_id_status     INTEGER NOT NULL
);

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( id_product );

CREATE TABLE rol (
    id_rol INTEGER NOT NULL,
    name   VARCHAR2(50) NOT NULL
);

ALTER TABLE rol ADD CONSTRAINT rol_pk PRIMARY KEY ( id_rol );

CREATE TABLE status (
    id_status INTEGER NOT NULL,
    name      VARCHAR2(50) NOT NULL
);

ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( id_status );

CREATE TABLE "User" (
    id_user          INTEGER NOT NULL,
    email            VARCHAR2(256) NOT NULL,
    full_name        VARCHAR2(100) NOT NULL,
    password         VARCHAR2(255) NOT NULL,
    phone            CHAR(8) NOT NULL,
    birth_date       DATE NOT NULL,
    creation_date    DATE NOT NULL,
    status_id_status INTEGER NOT NULL,
    rol_id_rol       INTEGER NOT NULL
);

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( id_user );

ALTER TABLE category
    ADD CONSTRAINT category_status_fk FOREIGN KEY ( status_id_status )
        REFERENCES status ( id_status );

ALTER TABLE client
    ADD CONSTRAINT client_user_fk FOREIGN KEY ( id_user )
        REFERENCES "User" ( id_user );

ALTER TABLE detail
    ADD CONSTRAINT detail_order_fk FOREIGN KEY ( order_id_order )
        REFERENCES "Order" ( id_order );

ALTER TABLE detail
    ADD CONSTRAINT detail_product_fk FOREIGN KEY ( product_id_product )
        REFERENCES product ( id_product );

ALTER TABLE "Order"
    ADD CONSTRAINT order_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE "Order"
    ADD CONSTRAINT order_user_fk FOREIGN KEY ( user_id_user )
        REFERENCES "User" ( id_user );

ALTER TABLE product
    ADD CONSTRAINT product_category_fk FOREIGN KEY ( category_id_category )
        REFERENCES category ( id_category );

ALTER TABLE product
    ADD CONSTRAINT product_status_fk FOREIGN KEY ( status_id_status )
        REFERENCES status ( id_status );

ALTER TABLE "User"
    ADD CONSTRAINT user_rol_fk FOREIGN KEY ( rol_id_rol )
        REFERENCES rol ( id_rol );

ALTER TABLE "User"
    ADD CONSTRAINT user_status_fk FOREIGN KEY ( status_id_status )
        REFERENCES status ( id_status );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
